In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import metrics

In [2]:
features = pd.read_csv('kagglefull-ner.csv')
list(features.columns)

['Unnamed: 0',
 'TF',
 'Bigram TF',
 'No. of Stop_words',
 'Out of Context',
 'Arts, Culture, Entertainment, Sports',
 'Conspiracy',
 'Business and Industrial',
 'economy, business and finance',
 'Religion and belief',
 'Law, Government and Politics',
 'Education',
 'Technology and Computing',
 'Science',
 'Sixltr',
 'conj',
 'interrog',
 'number',
 'negemo',
 'social',
 'certain',
 'percept',
 'focuspast',
 'focuspresent',
 'time',
 'ORG',
 'PERSON',
 'GPE']

In [3]:
features.drop(columns=['Unnamed: 0'], inplace=True)
features.fillna(0,inplace=True)
features.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2145 entries, 0 to 2144
Data columns (total 27 columns):
TF                                      2145 non-null float64
Bigram TF                               2145 non-null int64
No. of Stop_words                       2145 non-null float64
Out of Context                          2145 non-null float64
Arts, Culture, Entertainment, Sports    2145 non-null float64
Conspiracy                              2145 non-null float64
Business and Industrial                 2145 non-null float64
economy, business and finance           2145 non-null float64
Religion and belief                     2145 non-null float64
Law, Government and Politics            2145 non-null float64
Education                               2145 non-null float64
Technology and Computing                2145 non-null float64
Science                                 2145 non-null float64
Sixltr                                  2145 non-null float64
conj                       

In [4]:
df= pd.read_pickle('kaggle_final.pkl')
list(df.columns)

['emergent_page',
 'claim',
 'claim_description',
 'claim_label',
 'tags',
 'claim_source_domain',
 'claim_course_url',
 'date',
 'body',
 'page_domain',
 'page_url',
 'page_headline',
 'page_position',
 'page_shares',
 'page_order',
 'claim_pos',
 'spelling',
 'grammar_error',
 'topic modelling',
 'clean_text',
 'TF',
 'out of context terms',
 'out of context final',
 'Textrazor_category',
 'Textrazor_topic',
 'Topics_category',
 'Topics_topic',
 'score_category',
 'score_topic',
 'category_score_final',
 'category_list_final',
 'topic_score_final',
 'topic_list_final',
 'TF_temp',
 'formula 1',
 'formula 2',
 'bigram TF',
 'bigram TF final',
 'No. of stop_words',
 'arts, culture and entertainment',
 'Conspiracy',
 'crime, law and justice',
 'Criticism of journalism',
 'Advertising video on demand',
 'computing and information technology',
 'agriculture',
 'energy and resource',
 'economy, business and finance',
 'Harassment',
 'Cyberspace',
 'religion and belief',
 'Politics and tech

In [5]:
print(len(df))
print(len(features))

2145
2145


In [6]:
X=features.iloc[:,:].values

In [7]:
#creating the dependant variable y
y= df.loc[:,['claim_label']]

In [8]:
y[1:50]

claim_label
1   Unverified
2   Unverified
3   Unverified
4   Unverified
5   Unverified
6   Unverified
7   Unverified
8   Unverified
9   Unverified
10  Unverified
11  Unverified
12  Unverified
13  Unverified
14  Unverified
15  Unverified
16  Unverified
17  Unverified
18  Unverified
19  Unverified
20  Unverified
21  Unverified
22  Unverified
23  Unverified
24       FALSE
25       FALSE
26       FALSE
27       FALSE
28       FALSE
29       FALSE
30       FALSE
31       FALSE
32       FALSE
33       FALSE
34       FALSE
35       FALSE
36       FALSE
37       FALSE
38       FALSE
39       FALSE
40       FALSE
41        TRUE
42        TRUE
43        TRUE
44        TRUE
45        TRUE
46        TRUE
47        TRUE
48        TRUE
49        TRUE

In [9]:
print(type(y))
print(type(X))

<class 'pandas.core.frame.DataFrame'>
<class 'numpy.ndarray'>


In [10]:
#mapping the labels to respective numeric terms
dict = {'FALSE' : 0, 'TRUE' : 1, 'Unverified' : 2}

In [11]:
y=y.replace({"claim_label": dict})

In [12]:
y=y.iloc[:,0].values

In [13]:
print(type(y))
print(type(X))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [14]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [15]:
# #splitting our data into train and test, 20% test and 80% train
# from sklearn.model_selection import train_test_split
# X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20, random_state = 0)

In [16]:
#Stratified split
from sklearn.model_selection import StratifiedShuffleSplit
sss = StratifiedShuffleSplit( n_splits=5, test_size=0.2, random_state=0)
for train_index, test_index in sss.split(X, y):
    print("TRAIN:", train_index, "TEST:", test_index)
    X_train, X_test = X[train_index], X[test_index]
    y_train, y_test = y[train_index], y[test_index]

TRAIN: [ 566 1199   38 ... 1407 1298 1711] TEST: [1533   66 2074  829  333  112 1669  281 1590 1163  771 2037 1293  550
 1445 1283 1404  435 1139  353  808 1819 1464 1458  643  377 1578 1127
 2053 1814 1065 1549 1532 2002  700 1707 1605  604 1004 1140 1011   97
 1922  597  444  859   98 1772 1250 1550 1261  975 2114 1591  384   44
 1290 2066  102 1180  716 1631 1897 1048 2089 1366  800 1583  907  397
 1785 1780  675  131  924  284 1092 1189 1259  594  470  635 1378 1211
  513  496  361 1517  538 1221 1175  796  698 1714   63 1418  994 2067
 1018 1260  336  743 2102  711  864 2078 1311 1244 1188  702 2042 2121
 1902 2133 1703 1474 1025 1472  463  300  248  468 1177  531 1453 1208
  790  659  202  804  873 1999 1232 1704 1050 2060  208  885 1960 1170
 1565 1149 1867 1468  495  309  517  374 1984 2003 1268 1410  500 1384
 2058  601  846  670 1365  684 2076 1933 2041  288 1601 1811 2016  731
 1340 2139 1801  803 1113 2109 1419 1713 1483  576 2000  886 1923  515
  979  982 1427  814 2094  9

In [17]:
print(len(X_train))
print(len(X_test))

1716
429


In [18]:
#Applying feature scaling so that training is faster
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [19]:
# #Applying LDA
# from sklearn.discriminant_analysis import LinearDiscriminantAnalysis as LDA
# lda = LDA(n_components = 5)
# X_train = lda.fit_transform(X_train, y_train)
# X_test = lda.transform(X_test)

In [20]:
#classifier naive bayes
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(X_train, y_train)

y_pred = classifier.predict(X_test)

# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)


print("Confusion matrix with Naive Bayes: ")
print(cm)
print("Accuracy with Naive Bayes: ")

from sklearn.metrics import accuracy_score
print(accuracy_score(y_test, y_pred))

print("Accuracy and Standard deviation after applying k-fold cross validation, k=10")
# Applying k-Fold Cross Validation
from sklearn.model_selection import cross_val_score
accuracies = cross_val_score(estimator = classifier, X = X_train, y = y_train, cv = 10)
print(accuracies.mean())
print(accuracies.std())

# from sklearn import  metrics
# roc_curve = metrics.plot_roc_curve(classifier, X_test, y_test)
# plt.show()

Confusion matrix with Naive Bayes: 
[[ 44   5  61]
 [  4  70  73]
 [  0   0 172]]
Accuracy with Naive Bayes: 
0.6666666666666666
Accuracy and Standard deviation after applying k-fold cross validation, k=10
0.6847152355729131
0.034455787730856925


In [21]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators = 5, criterion = 'entropy', random_state = 42, max_features=None)
classifier.fit(X_train, y_train)

y_pred = classifier.predict(X_test)

from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)

print("Confusion matrix with random forests: ")
print(cm)
print("Accuracy with random forests: ")

from sklearn.metrics import accuracy_score
print(accuracy_score(y_test, y_pred))

print("Accuracy and Standard deviation after applying k-fold cross validation, k=10")
# Applying k-Fold Cross Validation
from sklearn.model_selection import cross_val_score
accuracies = cross_val_score(estimator = classifier, X = X_train, y = y_train, cv = 10)
print(accuracies.mean())
print(accuracies.std())

# Applying Grid Search to find the best model and the best parameters
from sklearn.model_selection import GridSearchCV
parameters = [{'n_estimators': [4,5,6,7,8,10,11,12], 'criterion': ['entropy', 'gini'], 'random_state':[42], 'max_features':['auto', "sqrt", 'log2', None ]}
             ]
    
grid_search = GridSearchCV(estimator = classifier,
                           param_grid = parameters,
                           scoring = 'accuracy',
                           cv = 10,
                           n_jobs = -1)
grid_search = grid_search.fit(X_train, y_train)
best_accuracy = grid_search.best_score_
best_parameters = grid_search.best_params_

print("Accuracy with Grid search :")
print(best_accuracy)

print("Best parameters for random forests for best accuracy")
print(best_parameters)

# from sklearn import  metrics
# roc_curve = metrics.plot_roc_curve(classifier, X_test, y_test)
# plt.show()

Confusion matrix with random forests: 
[[110   0   0]
 [  0 147   0]
 [  0   0 172]]
Accuracy with random forests: 
1.0
Accuracy and Standard deviation after applying k-fold cross validation, k=10
0.9964980280157759
0.00534937937936848
Accuracy with Grid search :
0.9994172494172494
Best parameters for random forests for best accuracy
{'criterion': 'entropy', 'max_features': 'auto', 'n_estimators': 7, 'random_state': 42}


In [38]:
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier(criterion = 'entropy', random_state = 42)
classifier.fit(X_train, y_train)

y_pred = classifier.predict(X_test)

from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)

print("Confusion matrix with decision tree: ")
print(cm)
print("Accuracy with decision tree: ")

from sklearn.metrics import accuracy_score
print(accuracy_score(y_test, y_pred))

print("Accuracy and Standard deviation after applying k-fold cross validation, k=10")
# Applying k-Fold Cross Validation
from sklearn.model_selection import cross_val_score
accuracies = cross_val_score(estimator = classifier, X = X_train, y = y_train, cv = 10)
print(accuracies.mean())
print(accuracies.std())



Confusion matrix with decision tree: 
[[110   0   0]
 [  0 147   0]
 [  0   0 172]]
Accuracy with decision tree: 
1.0
Accuracy and Standard deviation after applying k-fold cross validation, k=10
0.9976676186590506
0.003872961533728854


In [39]:
classifier.feature_importances_

array([0.03322395, 0.        , 0.03277438, 0.06226223, 0.05569196,
       0.        , 0.        , 0.04365634, 0.        , 0.02543621,
       0.        , 0.        , 0.06803644, 0.00168958, 0.02923059,
       0.02145374, 0.12193257, 0.08496351, 0.03453018, 0.        ,
       0.14414954, 0.12274659, 0.11228228, 0.        , 0.        ,
       0.        , 0.0059399 ])

In [40]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors = 6, p = 1)
classifier.fit(X_train, y_train)

y_pred = classifier.predict(X_test)

from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)

print("Confusion matrix with K Nearest Neighbours: ")
print(cm)
print("Accuracy with K nearest Neighbours: ")

from sklearn.metrics import accuracy_score
print(accuracy_score(y_test, y_pred))

print("Accuracy and Standard deviation after applying k-fold cross validation, k=10")
# Applying k-Fold Cross Validation
from sklearn.model_selection import cross_val_score
accuracies = cross_val_score(estimator = classifier, X = X_train, y = y_train, cv = 10)
print(accuracies.mean())
print(accuracies.std())

# Applying Grid Search to find the best model and the best parameters
from sklearn.model_selection import GridSearchCV
parameters = [{'n_neighbors': [4,3,5,6,7,8], 'p':[1, 2], "algorithm":['auto', 'ball_tree', 'kd_tree', 'brute'] }]
grid_search = GridSearchCV(estimator = classifier,
                           param_grid = parameters,
                           scoring = 'accuracy',
                           cv = 10,
                           n_jobs = -1)
grid_search = grid_search.fit(X_train, y_train)
best_accuracy = grid_search.best_score_
best_parameters = grid_search.best_params_

print("Accuracy with Grid search :")
print(best_accuracy)

print("Best parameters for KNN for best accuracy")
print(best_parameters)
# from sklearn import  metrics
# roc_curve = metrics.plot_roc_curve(classifier, X_test, y_test)
# plt.show()

Confusion matrix with K Nearest Neighbours: 
[[102   6   2]
 [  0 147   0]
 [  2   0 170]]
Accuracy with K nearest Neighbours: 
0.9766899766899767
Accuracy and Standard deviation after applying k-fold cross validation, k=10
0.9813477492180063
0.009347553573330471
Accuracy with Grid search :
0.9970896232830138
Best parameters for KNN for best accuracy
{'algorithm': 'auto', 'n_neighbors': 4, 'p': 2}


In [41]:
import xgboost
from xgboost import XGBClassifier
classifier = XGBClassifier()
classifier.fit(X_train, y_train)

y_pred = classifier.predict(X_test)

from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)

print("Confusion matrix with XGBoost: ")
print(cm)
print("Accuracy with XGBoost: ")

from sklearn.metrics import accuracy_score
print(accuracy_score(y_test, y_pred))

print("Accuracy and Standard deviation after applying k-fold cross validation, k=10")
# Applying k-Fold Cross Validation
from sklearn.model_selection import cross_val_score
accuracies = cross_val_score(estimator = classifier, X = X_train, y = y_train, cv = 10)
print(accuracies.mean())
print(accuracies.std())

# from sklearn import  metrics
# roc_curve = metrics.plot_roc_curve(classifier, X_test, y_test)
# plt.show()

Confusion matrix with XGBoost: 
[[110   0   0]
 [  0 147   0]
 [  0   0 172]]
Accuracy with XGBoost: 
1.0
Accuracy and Standard deviation after applying k-fold cross validation, k=10
0.9982490140078879
0.0026746896896842572


In [42]:
from sklearn.svm import SVC
classifier = SVC(kernel = 'rbf', random_state = 0, gamma='scale')
classifier.fit(X_train, y_train)

y_pred = classifier.predict(X_test)

from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)

print("Confusion matrix with kernel SVM: ")
print(cm)
print("Accuracy with kernel SVM: ")

from sklearn.metrics import accuracy_score
print(accuracy_score(y_test, y_pred))

print("Accuracy and Standard deviation after applying k-fold cross validation, k=10")
# Applying k-Fold Cross Validation
from sklearn.model_selection import cross_val_score
accuracies = cross_val_score(estimator = classifier, X = X_train, y = y_train, cv = 10)
print(accuracies.mean())
print(accuracies.std())

# Applying Grid Search to find the best model and the best parameters
from sklearn.model_selection import GridSearchCV
parameters = [ {'C': [1, 10, 100, 1000], 'kernel': ['rbf'], 'gamma': ['scale','auto']}]
grid_search = GridSearchCV(estimator = classifier,
                           param_grid = parameters,
                           scoring = 'accuracy',
                           cv = 10,
                           n_jobs = -1)
grid_search = grid_search.fit(X_train, y_train)
best_accuracy = grid_search.best_score_
best_parameters = grid_search.best_params_

print("Accuracy with Grid search :")
print(best_accuracy)

print("Best parameters for SVM for best accuracy")
print(best_parameters)

# roc_curve = plot_roc_curve(classifier, X_test, y_test)
# plt.show()

Confusion matrix with kernel SVM: 
[[108   0   2]
 [  0 147   0]
 [  0   0 172]]
Accuracy with kernel SVM: 
0.9953379953379954
Accuracy and Standard deviation after applying k-fold cross validation, k=10
0.9935910512715898
0.007106906954980074
Accuracy with Grid search :
0.9994152046783625
Best parameters for SVM for best accuracy
{'C': 10, 'gamma': 'scale', 'kernel': 'rbf'}
