In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import metrics

In [2]:
features = pd.read_csv('kaggle-ner.csv')
list(features.columns)

['Unnamed: 0',
 'TF',
 'Bigram TF',
 'No. of Stop_words',
 'Out of Context',
 'Arts, Culture, Entertainment, Sports',
 'Conspiracy',
 'Business and Industrial',
 'economy, business and finance',
 'Religion and belief',
 'Law, Government and Politics',
 'Education',
 'Technology and Computing',
 'Science',
 'Sixltr',
 'conj',
 'interrog',
 'number',
 'negemo',
 'social',
 'certain',
 'percept',
 'focuspast',
 'focuspresent',
 'time',
 'ORG',
 'PERSON',
 'GPE']

In [3]:
features.drop(columns=['Unnamed: 0'], inplace=True)
features.fillna(0,inplace=True)
features.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 107 entries, 0 to 106
Data columns (total 27 columns):
TF                                      107 non-null float64
Bigram TF                               107 non-null int64
No. of Stop_words                       107 non-null float64
Out of Context                          107 non-null float64
Arts, Culture, Entertainment, Sports    107 non-null float64
Conspiracy                              107 non-null float64
Business and Industrial                 107 non-null float64
economy, business and finance           107 non-null float64
Religion and belief                     107 non-null float64
Law, Government and Politics            107 non-null float64
Education                               107 non-null float64
Technology and Computing                107 non-null float64
Science                                 107 non-null float64
Sixltr                                  107 non-null float64
conj                                    107

In [4]:
df= pd.read_pickle('KaggleEmergent-dup.pkl')
list(df.columns)

['emergent_page',
 'claim',
 'claim_description',
 'claim_label',
 'tags',
 'claim_source_domain',
 'claim_course_url',
 'date',
 'body',
 'page_domain',
 'page_url',
 'page_headline',
 'page_position',
 'page_shares',
 'page_order',
 'claim_pos',
 'spelling',
 'grammar_error',
 'topic modelling',
 'clean_text',
 'TF',
 'out of context terms',
 'out of context final',
 'Textrazor_category',
 'Textrazor_topic',
 'Topics_category',
 'Topics_topic',
 'score_category',
 'score_topic',
 'category_score_final',
 'category_list_final',
 'topic_score_final',
 'topic_list_final',
 'TF_temp',
 'formula 1',
 'formula 2',
 'bigram TF',
 'bigram TF final',
 'No. of stop_words',
 'arts, culture and entertainment',
 'Conspiracy',
 'crime, law and justice',
 'Criticism of journalism',
 'Advertising video on demand',
 'computing and information technology',
 'agriculture',
 'energy and resource',
 'economy, business and finance',
 'Harassment',
 'Cyberspace',
 'religion and belief',
 'Politics and tech

In [5]:
print(len(df))
print(len(features))

107
107


In [6]:
X=features.iloc[:,:].values

In [7]:
#creating the dependant variable y
y= df.loc[:,['claim_label']]

In [8]:
y[1:50]

claim_label
3    Unverified
12   Unverified
24        FALSE
34        FALSE
41         TRUE
52        FALSE
56        FALSE
63        FALSE
66   Unverified
78   Unverified
86        FALSE
102       FALSE
113  Unverified
119       FALSE
135  Unverified
140        TRUE
146  Unverified
156       FALSE
164  Unverified
177        TRUE
182        TRUE
192        TRUE
213  Unverified
224  Unverified
241       FALSE
248  Unverified
263        TRUE
274        TRUE
286        TRUE
304       FALSE
312  Unverified
322  Unverified
335       FALSE
354       FALSE
382  Unverified
465  Unverified
607  Unverified
615  Unverified
623  Unverified
647  Unverified
662  Unverified
671  Unverified
675       FALSE
688  Unverified
697       FALSE
700        TRUE
704       FALSE
708  Unverified
722       FALSE

In [9]:
print(type(y))
print(type(X))

<class 'pandas.core.frame.DataFrame'>
<class 'numpy.ndarray'>


In [10]:
#mapping the labels to respective numeric terms
dict = {'FALSE' : 0, 'TRUE' : 1, 'Unverified' : 2}

In [11]:
y=y.replace({"Label": dict})

In [12]:
y=y.iloc[:,0].values

In [13]:
print(type(y))
print(type(X))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [14]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [15]:
# #splitting our data into train and test, 20% test and 80% train
# from sklearn.model_selection import train_test_split
# X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20, random_state = 0)

In [16]:
#Stratified split
from sklearn.model_selection import StratifiedShuffleSplit
sss = StratifiedShuffleSplit( n_splits=5, test_size=0.2, random_state=0)
for train_index, test_index in sss.split(X, y):
    print("TRAIN:", train_index, "TEST:", test_index)
    X_train, X_test = X[train_index], X[test_index]
    y_train, y_test = y[train_index], y[test_index]

TRAIN: [ 99  49  64  36  59  52  33  61 103  67  79  72  54 106  84  77  24  48
  82  68 102   2  60   4  30  38   1  98  65  40  22  44  14  37  80  41
  86  28  93  42 105  71  45  34   6  51  10  32  95  88  89  94  47  83
  92  57  97  91  11  15  76  85  70  16 101  81  20  18  27  13  29  23
  74  17  50  87  46  73  66  19  43   9  75   8  78] TEST: [ 25  31  56  63  21  26  62  58  53   0 104  12  69  39  90 100   3  55
  35   7   5  96]
TRAIN: [ 94 100  43  20  99  42  83  40  59  64  67  23  97  31  21   0  76  19
  24  56 104  50  63  53  61  49  69  60  13  14  75  18   3   7  93  66
  88  15  89  79  47  45  48  52  32  54  65  85  37 102   4  92  36 101
  44  28  70   8  98  25  58  74  81  90  17  86  87   9 106  41  34  26
  77  29  10  95  55  51   2  84  78  68   1  12  35] TEST: [ 46  72  73  82  11  22 105  30 103  33  38  91   5  80  62   6  27  96
  57  16  71  39]
TRAIN: [ 43   2  36  24 101  59  45   5  70  65  72 102  33  93  12  28  34  39
  77  60   9  95 103

In [17]:
print(len(X_train))
print(len(X_test))

85
22


In [18]:
#Applying feature scaling so that training is faster
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [19]:
# #Applying LDA
# from sklearn.discriminant_analysis import LinearDiscriminantAnalysis as LDA
# lda = LDA(n_components = 5)
# X_train = lda.fit_transform(X_train, y_train)
# X_test = lda.transform(X_test)

In [20]:
#classifier naive bayes
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(X_train, y_train)

y_pred = classifier.predict(X_test)

# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)


print("Confusion matrix with Naive Bayes: ")
print(cm)
print("Accuracy with Naive Bayes: ")

from sklearn.metrics import accuracy_score
print(accuracy_score(y_test, y_pred))

print("Accuracy and Standard deviation after applying k-fold cross validation, k=10")
# Applying k-Fold Cross Validation
from sklearn.model_selection import cross_val_score
accuracies = cross_val_score(estimator = classifier, X = X_train, y = y_train, cv = 10)
print(accuracies.mean())
print(accuracies.std())

# from sklearn import  metrics
# roc_curve = metrics.plot_roc_curve(classifier, X_test, y_test)
# plt.show()

Confusion matrix with Naive Bayes: 
[[2 1 5]
 [0 1 4]
 [0 0 9]]
Accuracy with Naive Bayes: 
0.5454545454545454
Accuracy and Standard deviation after applying k-fold cross validation, k=10
0.5402777777777777
0.08412815400504338


In [25]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators = 5, criterion = 'entropy', random_state = 42, max_features=None)
classifier.fit(X_train, y_train)

y_pred = classifier.predict(X_test)

from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)

print("Confusion matrix with random forests: ")
print(cm)
print("Accuracy with random forests: ")

from sklearn.metrics import accuracy_score
print(accuracy_score(y_test, y_pred))

print("Accuracy and Standard deviation after applying k-fold cross validation, k=10")
# Applying k-Fold Cross Validation
from sklearn.model_selection import cross_val_score
accuracies = cross_val_score(estimator = classifier, X = X_train, y = y_train, cv = 10)
print(accuracies.mean())
print(accuracies.std())

# Applying Grid Search to find the best model and the best parameters
from sklearn.model_selection import GridSearchCV
parameters = [{'n_estimators': [4,5,6,7,8,10,11,12], 'criterion': ['entropy', 'gini'], 'random_state':[42], 'max_features':['auto', "sqrt", 'log2', None ]}
             ]
    
grid_search = GridSearchCV(estimator = classifier,
                           param_grid = parameters,
                           scoring = 'accuracy',
                           cv = 10,
                           n_jobs = -1)
grid_search = grid_search.fit(X_train, y_train)
best_accuracy = grid_search.best_score_
best_parameters = grid_search.best_params_

print("Accuracy with Grid search :")
print(best_accuracy)

print("Best parameters for random forests for best accuracy")
print(best_parameters)

# from sklearn import  metrics
# roc_curve = metrics.plot_roc_curve(classifier, X_test, y_test)
# plt.show()

Confusion matrix with random forests: 
[[4 0 4]
 [2 2 1]
 [4 0 5]]
Accuracy with random forests: 
0.5
Accuracy and Standard deviation after applying k-fold cross validation, k=10
0.611111111111111
0.1259225217404793
Accuracy with Grid search :
0.611111111111111
Best parameters for random forests for best accuracy
{'criterion': 'entropy', 'max_features': None, 'n_estimators': 5, 'random_state': 42}


In [26]:
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier(criterion = 'entropy', random_state = 42)
classifier.fit(X_train, y_train)

y_pred = classifier.predict(X_test)

from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)

print("Confusion matrix with decision tree: ")
print(cm)
print("Accuracy with decision tree: ")

from sklearn.metrics import accuracy_score
print(accuracy_score(y_test, y_pred))

print("Accuracy and Standard deviation after applying k-fold cross validation, k=10")
# Applying k-Fold Cross Validation
from sklearn.model_selection import cross_val_score
accuracies = cross_val_score(estimator = classifier, X = X_train, y = y_train, cv = 10)
print(accuracies.mean())
print(accuracies.std())



Confusion matrix with decision tree: 
[[3 3 2]
 [1 3 1]
 [1 3 5]]
Accuracy with decision tree: 
0.5
Accuracy and Standard deviation after applying k-fold cross validation, k=10
0.5291666666666666
0.1821987196903154


In [27]:
classifier.feature_importances_

array([0.        , 0.        , 0.08659356, 0.11802888, 0.0267215 ,
       0.        , 0.        , 0.        , 0.03072125, 0.        ,
       0.        , 0.05948605, 0.03382599, 0.        , 0.09085101,
       0.05142893, 0.13046006, 0.12180437, 0.15750178, 0.0622494 ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.03032723])

In [29]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors = 6, p = 1)
classifier.fit(X_train, y_train)

y_pred = classifier.predict(X_test)

from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)

print("Confusion matrix with K Nearest Neighbours: ")
print(cm)
print("Accuracy with K nearest Neighbours: ")

from sklearn.metrics import accuracy_score
print(accuracy_score(y_test, y_pred))

print("Accuracy and Standard deviation after applying k-fold cross validation, k=10")
# Applying k-Fold Cross Validation
from sklearn.model_selection import cross_val_score
accuracies = cross_val_score(estimator = classifier, X = X_train, y = y_train, cv = 10)
print(accuracies.mean())
print(accuracies.std())

# Applying Grid Search to find the best model and the best parameters
from sklearn.model_selection import GridSearchCV
parameters = [{'n_neighbors': [4,3,5,6,7,8], 'p':[1, 2], "algorithm":['auto', 'ball_tree', 'kd_tree', 'brute'] }]
grid_search = GridSearchCV(estimator = classifier,
                           param_grid = parameters,
                           scoring = 'accuracy',
                           cv = 10,
                           n_jobs = -1)
grid_search = grid_search.fit(X_train, y_train)
best_accuracy = grid_search.best_score_
best_parameters = grid_search.best_params_

print("Accuracy with Grid search :")
print(best_accuracy)

print("Best parameters for KNN for best accuracy")
print(best_parameters)
# from sklearn import  metrics
# roc_curve = metrics.plot_roc_curve(classifier, X_test, y_test)
# plt.show()

Confusion matrix with K Nearest Neighbours: 
[[4 0 4]
 [2 2 1]
 [1 1 7]]
Accuracy with K nearest Neighbours: 
0.5909090909090909
Accuracy and Standard deviation after applying k-fold cross validation, k=10
0.575
0.13525809804377611
Accuracy with Grid search :
0.575
Best parameters for KNN for best accuracy
{'algorithm': 'auto', 'n_neighbors': 6, 'p': 1}


In [30]:
import xgboost
from xgboost import XGBClassifier
classifier = XGBClassifier()
classifier.fit(X_train, y_train)

y_pred = classifier.predict(X_test)

from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)

print("Confusion matrix with XGBoost: ")
print(cm)
print("Accuracy with XGBoost: ")

from sklearn.metrics import accuracy_score
print(accuracy_score(y_test, y_pred))

print("Accuracy and Standard deviation after applying k-fold cross validation, k=10")
# Applying k-Fold Cross Validation
from sklearn.model_selection import cross_val_score
accuracies = cross_val_score(estimator = classifier, X = X_train, y = y_train, cv = 10)
print(accuracies.mean())
print(accuracies.std())

# from sklearn import  metrics
# roc_curve = metrics.plot_roc_curve(classifier, X_test, y_test)
# plt.show()

Confusion matrix with XGBoost: 
[[4 0 4]
 [0 3 2]
 [2 2 5]]
Accuracy with XGBoost: 
0.5454545454545454
Accuracy and Standard deviation after applying k-fold cross validation, k=10
0.5513888888888889
0.13566394801170817


In [31]:
from sklearn.svm import SVC
classifier = SVC(kernel = 'rbf', random_state = 0, gamma='scale')
classifier.fit(X_train, y_train)

y_pred = classifier.predict(X_test)

from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)

print("Confusion matrix with kernel SVM: ")
print(cm)
print("Accuracy with kernel SVM: ")

from sklearn.metrics import accuracy_score
print(accuracy_score(y_test, y_pred))

print("Accuracy and Standard deviation after applying k-fold cross validation, k=10")
# Applying k-Fold Cross Validation
from sklearn.model_selection import cross_val_score
accuracies = cross_val_score(estimator = classifier, X = X_train, y = y_train, cv = 10)
print(accuracies.mean())
print(accuracies.std())

# Applying Grid Search to find the best model and the best parameters
from sklearn.model_selection import GridSearchCV
parameters = [ {'C': [1, 10, 100, 1000], 'kernel': ['rbf'], 'gamma': ['scale','auto']}]
grid_search = GridSearchCV(estimator = classifier,
                           param_grid = parameters,
                           scoring = 'accuracy',
                           cv = 10,
                           n_jobs = -1)
grid_search = grid_search.fit(X_train, y_train)
best_accuracy = grid_search.best_score_
best_parameters = grid_search.best_params_

print("Accuracy with Grid search :")
print(best_accuracy)

print("Best parameters for SVM for best accuracy")
print(best_parameters)

# roc_curve = plot_roc_curve(classifier, X_test, y_test)
# plt.show()

Confusion matrix with kernel SVM: 
[[1 1 6]
 [0 3 2]
 [2 0 7]]
Accuracy with kernel SVM: 
0.5
Accuracy and Standard deviation after applying k-fold cross validation, k=10
0.6333333333333334
0.11354963019983164
Accuracy with Grid search :
0.6333333333333334
Best parameters for SVM for best accuracy
{'C': 1, 'gamma': 'scale', 'kernel': 'rbf'}
