In [1]:
from keras.models import Sequential 
from keras.layers import Dense 
from keras.utils import np_utils
from sklearn.preprocessing import LabelEncoder
from keras.utils.np_utils import to_categorical
from sklearn.utils import shuffle
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import preprocessing, model_selection
from sklearn.preprocessing import StandardScaler

C:\Users\adith\anaconda3\envs\ANZ\lib\site-packages\h5py\__init__.py:34: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.


In [2]:
features = pd.read_csv('kaggle-ner.csv')
list(features.columns)

['Unnamed: 0',
 'TF',
 'Bigram TF',
 'No. of Stop_words',
 'Out of Context',
 'Arts, Culture, Entertainment, Sports',
 'Conspiracy',
 'Business and Industrial',
 'economy, business and finance',
 'Religion and belief',
 'Law, Government and Politics',
 'Education',
 'Technology and Computing',
 'Science',
 'Sixltr',
 'conj',
 'interrog',
 'number',
 'negemo',
 'social',
 'certain',
 'percept',
 'focuspast',
 'focuspresent',
 'time',
 'ORG',
 'PERSON',
 'GPE']

In [3]:
df= pd.read_pickle('KaggleEmergent-dup.pkl')
list(df.columns)

['emergent_page',
 'claim',
 'claim_description',
 'claim_label',
 'tags',
 'claim_source_domain',
 'claim_course_url',
 'date',
 'body',
 'page_domain',
 'page_url',
 'page_headline',
 'page_position',
 'page_shares',
 'page_order',
 'claim_pos',
 'spelling',
 'grammar_error',
 'topic modelling',
 'clean_text',
 'TF',
 'out of context terms',
 'out of context final',
 'Textrazor_category',
 'Textrazor_topic',
 'Topics_category',
 'Topics_topic',
 'score_category',
 'score_topic',
 'category_score_final',
 'category_list_final',
 'topic_score_final',
 'topic_list_final',
 'TF_temp',
 'formula 1',
 'formula 2',
 'bigram TF',
 'bigram TF final',
 'No. of stop_words',
 'arts, culture and entertainment',
 'Conspiracy',
 'crime, law and justice',
 'Criticism of journalism',
 'Advertising video on demand',
 'computing and information technology',
 'agriculture',
 'energy and resource',
 'economy, business and finance',
 'Harassment',
 'Cyberspace',
 'religion and belief',
 'Politics and tech

In [4]:
features.drop(columns=['Unnamed: 0'], inplace=True)
features.fillna(0,inplace=True)
features.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 107 entries, 0 to 106
Data columns (total 27 columns):
TF                                      107 non-null float64
Bigram TF                               107 non-null int64
No. of Stop_words                       107 non-null float64
Out of Context                          107 non-null float64
Arts, Culture, Entertainment, Sports    107 non-null float64
Conspiracy                              107 non-null float64
Business and Industrial                 107 non-null float64
economy, business and finance           107 non-null float64
Religion and belief                     107 non-null float64
Law, Government and Politics            107 non-null float64
Education                               107 non-null float64
Technology and Computing                107 non-null float64
Science                                 107 non-null float64
Sixltr                                  107 non-null float64
conj                                    107

In [5]:
X=features.loc[:,['TF','Bigram TF','No. of Stop_words', 'Out of Context', 'Religion and belief', 'Law, Government and Politics',
 'Sixltr', 'conj', 'interrog', 'number', 'negemo', 'social', 'certain', 'percept', 'focuspast', 'focuspresent', 'time',
 'PERSON', 'ORG','GPE']]

In [6]:
#creating the dependant variable y
y= df.loc[:,['claim_label']]
#mapping the labels to respective numeric terms
dict = {'FALSE' : 0, 'TRUE' : 1, 'Unverified' : 2}
y=y.replace({"claim_label": dict})

In [7]:
y

claim_label
0               2
3               2
12              2
24              0
34              0
...           ...
1715            2
1732            2
2130            2
2134            2
2138            2

[107 rows x 1 columns]

In [8]:
y=y.iloc[:,0].values
y = np_utils.to_categorical(y)

In [9]:
y

array([[0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0

In [10]:
len(X)

107

In [11]:
print(type(y))
print(type(X))

<class 'numpy.ndarray'>
<class 'pandas.core.frame.DataFrame'>


In [12]:
train_x, test_x, train_y, test_y = model_selection.train_test_split(X,y,test_size = 0.2, random_state = 0)

In [13]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
train_x = sc.fit_transform(train_x)
test_x = sc.transform(test_x)

In [14]:
len(train_y)

85

In [34]:
input_dim = 20

from keras.optimizers import SGD
model = Sequential()
model.add(Dense(32, input_dim = input_dim ,kernel_initializer='he_uniform', bias_initializer='zeros', activation='relu'))
model.add(Dense(32,kernel_initializer='he_uniform', bias_initializer='zeros', activation='relu'))
model.add(Dense(8,kernel_initializer='he_uniform', bias_initializer='zeros', activation = 'relu'))
# model.add(Dense(10, activation = 'relu'))
model.add(Dense(3, activation='softmax'))
model.compile(loss='categorical_crossentropy', optimizer=SGD(lr=0.005), metrics=['accuracy'])

In [35]:
model.fit(train_x, train_y, epochs = 45, batch_size = 4, verbose=1)

Epoch 1/45
85/85 [==============================] - 0s 1ms/step - loss: 1.4957 - accuracy: 0.4471
Epoch 2/45
85/85 [==============================] - 0s 273us/step - loss: 1.2069 - accuracy: 0.4118
Epoch 3/45
85/85 [==============================] - 0s 259us/step - loss: 1.1169 - accuracy: 0.4471
Epoch 4/45
85/85 [==============================] - 0s 269us/step - loss: 1.0647 - accuracy: 0.4706
Epoch 5/45
85/85 [==============================] - 0s 277us/step - loss: 1.0303 - accuracy: 0.4471
Epoch 6/45
85/85 [==============================] - 0s 258us/step - loss: 1.0009 - accuracy: 0.4824
Epoch 7/45
85/85 [==============================] - 0s 258us/step - loss: 0.9733 - accuracy: 0.5059
Epoch 8/45
85/85 [==============================] - 0s 258us/step - loss: 0.9514 - accuracy: 0.5647
Epoch 9/45
85/85 [==============================] - 0s 258us/step - loss: 0.9279 - accuracy: 0.5647
Epoch 10/45
85/85 [==============================] - 0s 270us/step - loss: 0.9073 - accuracy: 0.5882
E

In [36]:
scores = model.evaluate(test_x, test_y)
print("\n%s: %.2f%%" % (model.metrics_names[1], scores[1]*100))

22/22 [==============================] - 0s 2ms/step

accuracy: 54.55%


In [37]:
y_pred= model.predict(test_x)
y_pred = np.argmax(y_pred, axis=-1)

In [38]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(np.argmax(test_y, axis=-1), y_pred)

print("Confusion matrix: ")
print(cm)

Confusion matrix: 
[[6 2 1]
 [3 2 2]
 [1 1 4]]
